# Generated by Django 3.1.2 on 2020-11-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0006_auto_20201107_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='blogweb.Comment'),
        ),
    ]
