# Generated by Django 3.1.2 on 2020-11-11 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0007_auto_20201107_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
