# Generated by Django 3.1.2 on 2020-11-15 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogweb', '0008_auto_20201111_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(max_length=300),
        ),
    ]
